// demo-common/apps/react/src/components/PrintOutputDialog.jsx
// 打印输出弹窗：服务端 PDF 与客户端静默打印两条链路收拢于此。
// 首次打开时各探测一次，之后靠「重新检测」按钮刷新；printData 随批量开关在对象/数组间切换。
import { useEffect, useRef, useState } from 'react'
import { PrintClient, WormPrintError } from '@worm-vue3-print/core/client'
import { checkRenderHealth, openPdfBlob, requestServerPdf } from '../render-client'
import { renderInBrowser } from '../browser-render'

const client = new PrintClient({ timeoutMs: 20000 })

export default function PrintOutputDialog({ visible, onClose, designerRef, printData, currentSampleName, baseUrl }) {
  // ── 服务端 PDF ──
  const [renderStatus, setRenderStatus] = useState('checking')
  const [renderStatusText, setRenderStatusText] = useState('渲染服务检测中…')
  const [renderStatusTitle, setRenderStatusTitle] = useState('探测 render 微服务 /render-api/health')
  const [rendering, setRendering] = useState(false)
  const [renderError, setRenderError] = useState('')
  const renderErrorTimer = useRef()

  // ── 客户端静默打印 ──
  const [clientStatus, setClientStatus] = useState('checking')
  const [clientStatusText, setClientStatusText] = useState('检测打印客户端…')
  const [clientPrinters, setClientPrinters] = useState([])
  const [selectedPrinter, setSelectedPrinter] = useState('')
  const [clientPrinting, setClientPrinting] = useState(false)
  const [clientMessage, setClientMessage] = useState('')
  const [clientMessageKind, setClientMessageKind] = useState('')
  const clientMsgTimer = useRef()
  const statusRegistered = useRef(false)
  const probed = useRef(false)

  async function refreshRenderStatus() {
    setRenderStatus('checking')
    setRenderStatusText('渲染服务检测中…')
    const health = await checkRenderHealth()
    if (!health) {
      setRenderStatus('offline')
      setRenderStatusText('渲染服务离线')
      setRenderStatusTitle('请启动 services/print-render')
      return
    }
    setRenderStatus('online')
    setRenderStatusText('渲染服务在线')
    setRenderStatusTitle(`活跃 ${health.activeRenders} / 并发 ${health.maxConcurrent} · 队列 ${health.queueLength}`)
  }

  function showRenderError(message) {
    setRenderError(message)
    clearTimeout(renderErrorTimer.current)
    renderErrorTimer.current = setTimeout(() => setRenderError(''), 5000)
  }

  function showClientMessage(message, kind = 'success') {
    setClientMessage(message)
    setClientMessageKind(kind)
    clearTimeout(clientMsgTimer.current)
    clientMsgTimer.current = setTimeout(() => {
      setClientMessage('')
      setClientMessageKind('')
    }, 5000)
  }

  async function refreshClientPrinters() {
    try {
      setClientPrinters(await client.listPrinters())
    } catch {
      setClientPrinters([])
    }
  }

  async function connectPrintClient() {
    setClientStatus('checking')
    setClientStatusText('检测打印客户端…')
    if (!statusRegistered.current) {
      statusRegistered.current = true
      client.onStatusChange(status => {
        if (status === 'connected') {
          setClientStatus('online')
          setClientStatusText('打印客户端在线')
          refreshClientPrinters()
        } else if (status === 'disconnected') {
          setClientStatus('offline')
          setClientStatusText('打印客户端离线')
        }
      })
    }
    try {
      await client.connect()
      setClientStatus('online')
      setClientStatusText('打印客户端在线')
      await refreshClientPrinters()
    } catch {
      setClientStatus('offline')
      setClientStatusText('打印客户端离线')
    }
  }

  // 懒初始化：首次打开弹窗时探测一次，之后仅保留状态
  useEffect(() => {
    if (!visible || probed.current) return
    probed.current = true
    refreshRenderStatus()
    connectPrintClient()
  }, [visible])

  useEffect(() => () => {
    clearTimeout(renderErrorTimer.current)
    clearTimeout(clientMsgTimer.current)
  }, [])

  if (!visible) return null

  function currentTemplateJson() {
    return JSON.parse(designerRef.current.getTemplateJson())
  }

  async function onServerPdf() {
    if (rendering) return
    let templateJson
    try {
      templateJson = currentTemplateJson()
    } catch {
      showRenderError('模板 JSON 解析失败')
      return
    }
    setRendering(true)
    setRenderError('')
    try {
      const pdf = await requestServerPdf(templateJson, printData, baseUrl)
      openPdfBlob(pdf, `print-${Date.now()}.pdf`)
      await refreshRenderStatus()
    } catch (err) {
      showRenderError(`PDF 生成失败：${err.message}`)
      await refreshRenderStatus()
    } finally {
      setRendering(false)
    }
  }

  /** 静默打印：本页两遍渲染出最终 HTML，直送本机客户端（WebSocket 127.0.0.1:17521） */
  async function onClientPrint() {
    if (clientPrinting) return
    let templateJson
    try {
      templateJson = currentTemplateJson()
    } catch {
      showClientMessage('模板 JSON 解析失败', 'error')
      return
    }
    setClientPrinting(true)
    setClientMessage('')
    setClientMessageKind('')
    try {
      const rendered = await renderInBrowser(templateJson, printData, baseUrl)
      const res = await client.printHtml(rendered, {
        printerName: selectedPrinter || undefined,
      }, currentSampleName ?? '打印模板')
      showClientMessage(`已提交静默打印，作业 ${res.jobId.slice(0, 8)}（${rendered.pageCount ?? 1} 页）`)
    } catch (err) {
      const code = err instanceof WormPrintError ? `[${err.code}] ` : ''
      showClientMessage(`静默打印失败：${code}${err.message}`, 'error')
    } finally {
      setClientPrinting(false)
    }
  }

  return (
    <div className="print-mask" onClick={onClose}>
      <div className="print-panel" onClick={e => e.stopPropagation()}>
        <div className="print-head">
          <span className="print-title">打印输出</span>
          <span className="print-close" onClick={onClose}>×</span>
        </div>
        <div className="print-body">
          <section className="print-card">
            <h3 className="card-title">服务端 PDF 打印</h3>
            <p className="card-desc">将当前画布模板与 demo 数据交由 render 微服务渲染，生成 PDF 后在浏览器新标签页打开。</p>
            <div className="card-row">
              <span className={`status ${renderStatus}`} title={renderStatusTitle}>
                <i className="status-dot"></i>{renderStatusText}
              </span>
              <button type="button" className="text-btn" onClick={refreshRenderStatus}>重新检测</button>
            </div>
            <button type="button" className="primary-btn" disabled={rendering || renderStatus !== 'online'} onClick={onServerPdf}>
              {rendering ? '生成中…' : '服务端 PDF'}
            </button>
            {renderError ? <p className="error-text">{renderError}</p> : null}
          </section>

          <section className="print-card">
            <h3 className="card-title">客户端静默打印</h3>
            <p className="card-desc">页面内用 core 同构管线完成两遍渲染，将最终 HTML 直送本机打印客户端（WebSocket 127.0.0.1:17521）静默出纸，客户端不再执行模板渲染。</p>
            <div className="card-row">
              <span className={`status ${clientStatus}`} title="本机打印客户端（WebSocket 127.0.0.1:17521）">
                <i className="status-dot"></i>{clientStatusText}
              </span>
              <button type="button" className="text-btn" onClick={connectPrintClient}>重新检测</button>
            </div>
            <div className="card-actions">
              <select
                className="printer-select"
                value={selectedPrinter}
                disabled={clientStatus !== 'online' || clientPrinting}
                title="选择目标打印机（留空为系统默认）"
                onChange={e => setSelectedPrinter(e.target.value)}
              >
                <option value="">系统默认打印机</option>
                {clientPrinters.map(p => (
                  <option key={p.name} value={p.name}>{p.name}{p.isDefault ? '（默认）' : ''}</option>
                ))}
              </select>
              <button type="button" className="primary-btn" disabled={clientPrinting || clientStatus !== 'online'} onClick={onClientPrint}>
                {clientPrinting ? '打印中…' : '客户端静默打印'}
              </button>
            </div>
            {clientMessage ? <p className={`message-text ${clientMessageKind}`}>{clientMessage}</p> : null}
          </section>
        </div>
      </div>
    </div>
  )
}

// demo/src/components/PrintOutputDialog.vue
<template>
  <Teleport to="body">
    <div v-if="open" class="print-mask" @click.self="emit('close')">
      <div class="print-panel">
        <div class="print-head">
          <span class="print-title">打印输出</span>
          <span class="print-close" @click="emit('close')">×</span>
        </div>
        <div class="print-body">
          <section class="print-card">
            <h3 class="card-title">服务端 PDF 打印</h3>
            <p class="card-desc">将当前画布模板与 demo 数据交由 render 微服务渲染，生成 PDF 后在浏览器新标签页打开。</p>
            <div class="card-row">
              <span class="status" :class="renderStatus" :title="renderStatusTitle">
                <i class="status-dot"></i>{{ renderStatusText }}
              </span>
              <button type="button" class="text-btn" @click="refreshRenderStatus">重新检测</button>
            </div>
            <button
              type="button"
              class="primary-btn"
              :disabled="rendering || renderStatus !== 'online'"
              @click="onServerPdf"
            >{{ rendering ? '生成中…' : '服务端 PDF' }}</button>
            <p v-if="renderError" class="error-text">{{ renderError }}</p>
          </section>

          <section class="print-card">
            <h3 class="card-title">客户端静默打印</h3>
            <p class="card-desc">页面内用 core 同构管线完成两遍渲染，将最终 HTML 直送本机打印客户端（WebSocket 127.0.0.1:17521）静默出纸，客户端不再执行模板渲染。</p>
            <div class="card-row">
              <span class="status" :class="clientStatus" title="本机打印客户端（WebSocket 127.0.0.1:17521）">
                <i class="status-dot"></i>{{ clientStatusText }}
              </span>
              <button type="button" class="text-btn" @click="connectPrintClient">重新检测</button>
            </div>
            <div class="card-actions">
              <select
                v-model="selectedPrinter"
                class="printer-select"
                :disabled="clientStatus !== 'online' || clientPrinting"
                title="选择目标打印机（留空为系统默认）"
              >
                <option value="">系统默认打印机</option>
                <option v-for="p in clientPrinters" :key="p.name" :value="p.name">
                  {{ p.name }}{{ p.isDefault ? '（默认）' : '' }}
                </option>
              </select>
              <button
                type="button"
                class="primary-btn"
                :disabled="clientPrinting || clientStatus !== 'online'"
                @click="onClientPrint"
              >{{ clientPrinting ? '打印中…' : '客户端静默打印' }}</button>
            </div>
            <p v-if="clientMessage" class="message-text" :class="clientMessageKind">{{ clientMessage }}</p>
          </section>
        </div>
      </div>
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { PrintClient, WormPrintError } from '@worm-vue3-print/client'
import type { PrinterInfo } from '@worm-vue3-print/client'
import {
  checkRenderHealth,
  requestServerPdf,
  openPdfBlob,
} from '../render-client'
import { renderInBrowser } from '../browser-render'

const props = defineProps<{
  open: boolean
  baseUrl: string
  templateName: string
  /** 当前打印数据：对象=单份；数组=批量（由宿主顶部开关切换，三端共用） */
  printData: Record<string, unknown> | Array<Record<string, unknown>>
  getTemplateJson: () => string | Record<string, unknown> | undefined
}>()

const emit = defineEmits<{
  close: []
  /** 本机字体清单；未连接或枚举失败时为 available:false */
  'client-fonts': [report: { available: boolean; fonts: string[] }]
}>()

// ── 服务端 PDF 打印 ──────────────────────────────────────────────────────
type RenderStatus = 'checking' | 'online' | 'offline'
const renderStatus = ref<RenderStatus>('checking')
const rendering = ref(false)
const renderError = ref('')

const renderStatusText = ref('渲染服务检测中…')
const renderStatusTitle = ref('探测 render 微服务 /render-api/health')

function setRenderOffline(message = '渲染服务未连接（请启动 services/print-render）') {
  renderStatus.value = 'offline'
  renderStatusText.value = '渲染服务离线'
  renderStatusTitle.value = message
}

async function refreshRenderStatus() {
  renderStatus.value = 'checking'
  renderStatusText.value = '渲染服务检测中…'
  const health = await checkRenderHealth()
  if (!health) {
    setRenderOffline()
    return
  }
  renderStatus.value = 'online'
  renderStatusText.value = '渲染服务在线'
  renderStatusTitle.value = `活跃 ${health.activeRenders} / 并发 ${health.maxConcurrent} · 队列 ${health.queueLength}`
}

let renderErrorTimer: ReturnType<typeof setTimeout> | undefined
function showRenderError(message: string) {
  renderError.value = message
  clearTimeout(renderErrorTimer)
  renderErrorTimer = setTimeout(() => (renderError.value = ''), 5000)
}

async function onServerPdf() {
  if (rendering.value) return
  let templateJson: Record<string, unknown> | null
  try {
    templateJson = resolveTemplateJson()
  } catch {
    showRenderError('模板 JSON 解析失败')
    return
  }
  if (!templateJson) {
    showRenderError('未获取到当前画布模板 JSON')
    return
  }

  rendering.value = true
  renderError.value = ''
  try {
    const pdf = await requestServerPdf(templateJson, props.printData, props.baseUrl)
    openPdfBlob(pdf, `purchase-receipt-${Date.now()}.pdf`)
    await refreshRenderStatus()
  } catch (err) {
    const message = err instanceof Error ? err.message : '服务端渲染失败'
    showRenderError(`PDF 生成失败：${message}`)
    await refreshRenderStatus()
  } finally {
    rendering.value = false
  }
}

// ── 桌面打印客户端静默打印 ──────────────────────────────────────────────
const client = new PrintClient({ timeoutMs: 20000 })
type ClientStatus = 'checking' | 'online' | 'offline'
const clientStatus = ref<ClientStatus>('checking')
const clientStatusText = ref('检测打印客户端…')
const clientPrinters = ref<PrinterInfo[]>([])
const selectedPrinter = ref('')
const clientPrinting = ref(false)
const clientMessage = ref('')
const clientMessageKind = ref<'success' | 'error' | ''>('')
let clientMsgTimer: ReturnType<typeof setTimeout> | undefined
let clientStatusRegistered = false

function showClientMessage(message: string, kind: 'success' | 'error' = 'success') {
  clientMessage.value = message
  clientMessageKind.value = kind
  clearTimeout(clientMsgTimer)
  clientMsgTimer = setTimeout(() => {
    clientMessage.value = ''
    clientMessageKind.value = ''
  }, 5000)
}

async function connectPrintClient() {
  clientStatus.value = 'checking'
  clientStatusText.value = '检测打印客户端…'
  if (!clientStatusRegistered) {
    clientStatusRegistered = true
    client.onStatusChange(s => {
      if (s === 'connected') {
        clientStatus.value = 'online'
        clientStatusText.value = '打印客户端在线'
        void refreshClientPrinters()
      } else if (s === 'disconnected') {
        clientStatus.value = 'offline'
        clientStatusText.value = '打印客户端离线'
        // 掉线后本机字体不再可知，必须撤回清单，否则会残留过期的可用范围标注
        emit('client-fonts', { available: false, fonts: [] })
      }
    })
  }
  try {
    await client.connect()
    clientStatus.value = 'online'
    clientStatusText.value = '打印客户端在线'
    await refreshClientPrinters()
    await refreshClientFonts()
  } catch {
    clientStatus.value = 'offline'
    clientStatusText.value = '打印客户端离线'
    emit('client-fonts', { available: false, fonts: [] })
  }
}

async function refreshClientFonts() {
  try {
    emit('client-fonts', await client.listFonts())
  } catch {
    emit('client-fonts', { available: false, fonts: [] })
  }
}

async function refreshClientPrinters() {
  try {
    clientPrinters.value = await client.listPrinters()
  } catch {
    clientPrinters.value = []
  }
}

async function onClientPrint() {
  if (clientPrinting.value) return
  let templateJson: Record<string, unknown> | null
  try {
    templateJson = resolveTemplateJson()
  } catch {
    showClientMessage('模板 JSON 解析失败', 'error')
    return
  }
  if (!templateJson) {
    showClientMessage('未获取到当前画布模板 JSON', 'error')
    return
  }

  clientPrinting.value = true
  clientMessage.value = ''
  clientMessageKind.value = ''
  try {
    // 浏览器侧两遍渲染（测量/分页/最终 HTML 全部在本页完成）；
    // printData 为数组时由 core 在浏览器侧合并多份为单个 HTML，再直送客户端静默打印
    const rendered = await renderInBrowser(templateJson, props.printData, props.baseUrl)
    const res = await client.printHtml(
      rendered,
      { printerName: selectedPrinter.value || undefined },
      props.templateName,
    )
    showClientMessage(`已提交静默打印，作业 ${res.jobId.slice(0, 8)}（${rendered.pageCount ?? 1} 页）`)
  } catch (err) {
    const code = err instanceof WormPrintError ? `[${err.code}] ` : ''
    const message = err instanceof Error ? err.message : '静默打印失败'
    showClientMessage(`静默打印失败：${code}${message}`, 'error')
  } finally {
    clientPrinting.value = false
  }
}

/** 获取画布模板 JSON：字符串则解析为对象；解析失败抛错由调用方提示 */
function resolveTemplateJson(): Record<string, unknown> | null {
  const rawJson = props.getTemplateJson()
  if (!rawJson) return null
  if (typeof rawJson === 'string') return JSON.parse(rawJson) as Record<string, unknown>
  return rawJson as unknown as Record<string, unknown>
}

// ── 懒初始化：首次打开时执行一次服务端检测与客户端连接，之后仅保留状态 ──
const initialized = ref(false)
watch(
  () => props.open,
  val => {
    if (val && !initialized.value) {
      initialized.value = true
      void refreshRenderStatus()
      void connectPrintClient()
    }
  },
)
</script>

<style scoped>
.print-mask {
  position: fixed;
  inset: 0;
  background: rgba(23, 32, 60, 0.45);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 9999;
}
.print-panel {
  width: min(560px, 92vw);
  max-height: 90vh;
  background: #fff;
  border-radius: 8px;
  box-shadow: 0 26px 60px rgba(23, 32, 60, 0.28);
  display: flex;
  flex-direction: column;
  overflow: hidden;
}
.print-head {
  display: flex;
  align-items: center;
  padding: 12px 16px;
  border-bottom: 1px solid #e9ecf2;
  flex-shrink: 0;
}
.print-title {
  font-size: 15px;
  font-weight: 600;
  color: #2a2e37;
}
.print-close {
  margin-left: auto;
  width: 26px;
  height: 26px;
  line-height: 24px;
  text-align: center;
  border-radius: 6px;
  font-size: 18px;
  color: #8b909c;
  cursor: pointer;
  user-select: none;
}
.print-close:hover {
  background: #f4f6fa;
  color: #2a2e37;
}
.print-body {
  padding: 16px;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 14px;
}
.print-card {
  border: 1px solid #e9ecf2;
  border-radius: 8px;
  padding: 14px 16px;
  background: #fbfcfe;
}
.card-title {
  margin: 0 0 4px;
  font-size: 14px;
  font-weight: 600;
  color: #2a2e37;
}
.card-desc {
  margin: 0 0 12px;
  font-size: 12px;
  color: #8b909c;
}
.card-row {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-bottom: 12px;
}
.card-actions {
  display: flex;
  align-items: center;
  gap: 10px;
}
.status {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  font-size: 12px;
  color: #5a667f;
  cursor: default;
}
.status-dot {
  width: 7px;
  height: 7px;
  border-radius: 50%;
  background: #c2c7d0;
}
.status.online {
  color: #16a34a;
}
.status.online .status-dot {
  background: #22c55e;
}
.status.offline {
  color: #dc2626;
}
.status.offline .status-dot {
  background: #ef4444;
}
.status.checking .status-dot {
  background: #f59e0b;
}
.text-btn {
  padding: 0;
  border: none;
  background: none;
  color: #165dff;
  font-size: 12px;
  cursor: pointer;
}
.text-btn:hover {
  text-decoration: underline;
}
.primary-btn {
  padding: 6px 14px;
  border: 1px solid #165dff;
  border-radius: 6px;
  background: #165dff;
  color: #fff;
  font-size: 13px;
  cursor: pointer;
}
.primary-btn:hover:not(:disabled) {
  background: #0e4fd8;
}
.primary-btn:disabled {
  border-color: #c2c7d0;
  background: #c2c7d0;
  cursor: not-allowed;
}
.printer-select {
  flex: 1;
  min-width: 0;
  padding: 5px 8px;
  border: 1px solid #d9dde6;
  border-radius: 6px;
  font-size: 12px;
  color: #2a2e37;
  background: #fff;
}
.printer-select:disabled {
  background: #f4f6fa;
  color: #9aa1af;
  cursor: not-allowed;
}
.error-text {
  margin: 10px 0 0;
  font-size: 12px;
  color: #dc2626;
}
.message-text {
  margin: 10px 0 0;
  font-size: 12px;
}
.message-text.success {
  color: #16a34a;
}
.message-text.error {
  color: #dc2626;
}
</style>
